// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ArelavSwiftUITools",
    platforms: [
        .iOS("18.1")
    ],
    products: [
        .library(
            name: "ArelavSwiftUITools",
            targets: ["ArelavSwiftUITools"]
        ),  
        .iOSApplication(
            name: "ArelavSwiftUIToolsDemo",
            targets: ["ArelavSwiftUIToolsDemo"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .images),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .target(
            name: "ArelavSwiftUITools",
            dependencies: []
        ),
        .executableTarget(
            name: "ArelavSwiftUIToolsDemo",
            dependencies: ["ArelavSwiftUITools"],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
