// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ArelavTools",
    platforms: [
        .iOS("18.1")
    ],
    products: [
        .library(
            name: "ArelavSwiftTools",
            targets: ["ArelavSwiftTools"]
        )
    ],
    targets: [
        .target(
            name: "ArelavSwiftTools",
            dependencies: []
        )
    ]
)